version: "3.9"

services:
  db:
    image: postgres:15
    container_name: taskora-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskora
    ports:
      - "5432:5432"

  api:
    build: ./apps/api
    container_name: taskora-api
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/taskora

  web:
    build: ./apps/web
    container_name: taskora-web
    ports:
      - "3000:3000"
    depends_on:
      - api