version: "3.9"

services:
  db:
    image: postgres:15
    container_name: taskora-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskora
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    container_name: taskora-api
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DATABASE_URL: postgresql://postgres:password@db:5432/taskora

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    container_name: taskora-web
    restart: always
    depends_on:
      - api
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000

volumes:
  postgres_data: